# don't build tags, it's redundant
if: tag IS blank
language: java
before_script:
  - echo $PATH
  - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
addons:
  apt:
    packages:
      - libgconf-2-4
install: true
script:
  - mvn install
  - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
  - echo $APPLITOOLS_BATCH_ID
  - mvn -DTest=SlackIntegrationTest test