# don't build tags, it's redundant
if: tag IS blank
language: java
java:
addons:
  apt:
    packages:
      - libgconf-2-4
script:
  - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
  - echo $APPLITOOLS_BATCH_ID