# don't build tags, it's redundant
if: tag IS blank
language: java
before_script:
  - echo $PATH
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser
addons:
  apt:
    packages:
      - libgconf-2-4
install: true
script:
  - mvn install
  - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
  - echo $APPLITOOLS_BATCH_ID
  - mvn -DTest=SlackIntegrationTest test